---
title: "data_nata_visualize"
author: "Alexandra Larsen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Input file: v1/Output/NATA_2014_US.csv
# Output file: v2/Plots/NATA_data
```

```{r}
# Load libraries
library(MplusAutomation)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(rgeos)
library(rgdal)
library(maptools)
library(stringr)
library(tigris)
library(mapproj)
library(RColorBrewer)
```

```{r}
source("/home/guest/spatial-ses-lcm/alex/v2/utils/plot_making.R")
source("/home/guest/spatial-ses-lcm/alex//v1/utils/pollutant_names.R")
source("/home/guest/spatial-ses-lcm/alex//v2/utils/variable_names.R")
```


```{r}
# import NC data frame
NC_df = read_csv("/home/guest/spatial-ses-lcm/alex/v1/Output/NATA_2014_NC.csv")
NC_df = as.data.frame(NC_df)
```

```{r}
# add a column for the percentile of each pollutant
NC_df$perc = rep(0, nrow(NC_df))
for (i in 1:nrow(nata_pollutants)) {
  w <- which(NC_df$`Pollutant Name`== nata_pollutants$nms[i])
  NC_df$perc[w] <- 100*ecdf(NC_df[w, "Total Conc"])(NC_df[w, "Total Conc"])
}
```

```{r}
# convert Tract to character
NC_df$Tract <- with(NC_df, as.character(as.numeric(Tract)))
```

```{r}
# convert to wide
NC_dfw <- NC_df %>%
  select(Tract, `Pollutant Name`, perc) %>%
  spread(`Pollutant Name`, perc)
```

```{r}
# get map data for NC
use_cache <- FALSE
map_df <- tbl_df(census_map_df(NC_dfw, "NC"))
```

```{r}
# TODO: make sure there aren't any space in the graphic's filename 
my_poln_vrbs <- toupper(poln_vrbs$orig)
```

```{r}
# loop through each pollutant; make map
for (p in my_poln_vrbs) {

  plot_df <- map_df %>%
    select(p, long, lat, order, hole, piece, Tract, group)
  colnames(plot_df)[1] <- "value"
  plot_df %>%
    ggplot(aes(x=long, y=lat, group=group)) + 
    geom_polygon(aes(fill=value), show.legend = T) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) + 
    scale_fill_gradientn(colors=rev(my_pal(8, "RdYlBu"))[-c(2)], limits=c(0, 100), name = "Percentile")+
    #scale_fill_viridis_c(option = "magma", direction = -1, name = p, limits=c(0, 100)) + 
    ggtitle(p) +
    theme_bw()+
    theme(plot.title = element_text(hjust = 0.5),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank())
  ggsave(filename = sprintf("/home/guest/spatial-ses-lcm/alex/v2/Plots/NATA_data/NATA_2014_NC_%s.png", str_replace_all(p, " ", "_")))
  
}

```


