abbrv <- c("BUTA", "ACET", "BENZENE", "CARBON", "DIESEL", "ETHYL", "FORM", "HEXANE", "LEAD", "MANG", "MERC", "METH", "METHYL", "NICK", "TOLUENE", "XYLENE")
nms <- c("1,3-BUTADIENE", "ACETALDEHYDE", "BENZENE", "CARBON TETRACHLORIDE", "DIESEL PM", "ETHYLBENZENE", "FORMALDEHYDE", "HEXANE", "LEAD COMPOUNDS", "METHANOL", 
         "METHYL CHLORIDE (CHLOROMETHANE)", "TOLUENE", "XYLENES (MIXED ISOMERS)", "MANGANESE COMPOUNDS", "MERCURY COMPOUNDS", "NICKEL COMPOUNDS")

nata_pollutants <- data.frame(abbrv = abbrv, nms = sort(nms))

#ses_params <- strsplit("PRFL_M PRFL_F LS_HS SINGLE HSHLDR_F NHBLK PA POV NO_VHCL RENT CROWD UNMPLYD PHONE", " ")[[1]]
